export enum UIPageEnum {
  BASE_HOME = '/index',
  BASE_HOME_NAME = 'HomeIndex',
  CHATBOT_ROOT = '/chat/1000',
  CHATBOT_NAME = 'Chatbot',
  CREATION = '/creation',
  CREATION_NAME = 'creation/index',
  DISCOVER = '/disc/index',
  DISCOVER_NAME = 'DiscoverIndex',
  REDIRECT = '/redirect',
  REDIRECT_NAME = 'Redirect',
  USER_CENTER = '/my/index',
  USER_CENTER_NAME = 'MyIndex',
  WECHAT_AUTHORIZE = '/wx_authorize',
  WECHAT_AUTHORIZE_NAME = 'WechatAuthorize',
}
